- hosts: clients

  tasks:
  - name: Install native games
    apt:
      name: [
        # games
        'wesnoth',
        'extremetuxracer',
        'btanks',
        'gamine',
        'gnome-chess',
        'neverputt',
        'bovo',
        'gcompris',
        'kapman',
        'ktuberling',
        'lskat',
        'supertux',
        'teeworlds',
        'games-tetris'
      ]
  - name: Install win games
    block:

      - name: Create games directory under .wine
        file:
          path: /home/test/.wine/drive_c/games/
          state: directory
          owner: test
          group: test
          mode: '0755'

      - name: Create games shortcut directory on Desktop
        file:
          path: /home/test/Desktop/Games/
          state: directory
          owner: test
          group: test
          mode: '0755'

      - name: Install starcraft
        unarchive:
          src: http://10.200.11.2:/games/starcraft.tar.gz
          dest: /home/test/.wine/drive_c/games/
          owner: test
          group: test
          remote_src: yes

          #      - name: Change ownership of wine directory
          #        file:
          #          path: /home/test/.wine/drive_c/games
          #          state: directory
          #          recurse: yes
          #          owner: test
          #          group: test
      
      - name: Install starcraft reg
        shell: wine start regedit.exe /home/test/.wine/drive_c/games/starcraft/starcraft.reg
        become_user: test

      - name: Download shortcut for starcraft
        get_url:
          url: http://10.200.11.2:/games/starcraft.desktop
          dest: /home/test/Desktop/Games/
          owner: test
          group: test         
          mode: '0550'

      - name: Install cs
        unarchive:
          src: http://10.200.11.2:/games/cs.tar.gz
          dest: /home/test/.wine/drive_c/games/
          owner: test
          group: test
          remote_src: yes

      - name: Download shortcut for cs
        get_url:
          url: http://10.200.11.2:/games/cs.desktop
          dest: /home/test/Desktop/Games/
          owner: test
          group: test
          mode: '0550'

          #      - name: fix permissions in shortcuts dir
          #        file:
          #          path: /home/test/Desktop/Games/
          #          state: directory
          #          owner: test
          #          group: test
          #          recurse: yes
          #
          #      - name: fix permissions in games dir
          #        file:
          #          path: /home/test/.wine/drive_c/games
          #          state: directory
          #          owner: test
          #          group: test
          #          recurse: yes


