- hosts: clients
  become: true

  tasks:
  - name: Install packages
    apt:
      name: [
        # games
        'wesnoth',
        'extremetuxracer',
        'btanks',
        'gamine',
        'gnome-chess',
        'neverputt',
        'bovo',
        'gcompris',
        'kapman',
        'ktuberling',
        'lskat',
        'supertux',
        'teeworlds'
      ]
