- hosts: clients

  tasks:
  - name: Install native games and apps
    apt:
      name: [
        # games
        'wesnoth',
        'extremetuxracer',
        'btanks',
        'gamine',
        'gnome-chess',
        'neverputt',
        'bovo',
        'gcompris',
        'kapman',
        'ktuberling',
        'lskat',
        'supertux',
        'teeworlds',
        'games-tetris',
        'freeciv',
        '0ad',
        'opencity',
        'openttd',
        #apps
        'kdenlive',
        'astrometry.net',
        'kalzium',
        'kbruch',
        'kgeography',
        'kig',
        'kolourpaint',
        'kruler',
        'kstars',
        'mpv',
        'smplayer',
        'timidity',
        'xplanet',
        'vlc',
        #system
        'osspd-pulseaudio'
      ]
  - name: Install win games
    block:

### create directory
      - name: Create games directory under .wine
        file:
          path: /home/test/.wine/drive_c/games/
          state: directory
          owner: test
          group: test
          mode: '0755'

      - name: Create games shortcut directory on Desktop
        file:
          path: /home/test/.local/share/applications/
          state: directory
          owner: test
          group: test
          mode: '0755'
### install starcraft
      - name: Install starcraft
        unarchive:
          src: http://10.200.11.2:/games/starcraft.tar.gz
          dest: /home/test/.wine/drive_c/games/
          owner: test
          group: test
          remote_src: yes

      - name: Install starcraft reg
        shell: /usr/bin/regedit-development /home/test/.wine/drive_c/games/starcraft/starcraft.reg
        become: yes
        become_user: test

      - name: Download shortcut for starcraft
        get_url:
          url: http://10.200.11.2:/games/starcraft.desktop
          dest: /home/test/.local/share/applications/
          owner: test
          group: test         
          mode: '0555'
### install cs 1.6
      - name: Install cs
        unarchive:
          src: http://10.200.11.2:/games/cs.tar.gz
          dest: /home/test/.wine/drive_c/games/
          owner: test
          group: test
          remote_src: yes

      - name: Download shortcut for cs
        get_url:
          url: http://10.200.11.2:/games/cs.desktop
          dest: /home/test/.local/share/applications/
          owner: test
          group: test
          mode: '0555'
### install plantsvszombies
      - name: Install plantsvszombies
        unarchive:
          src: http://10.200.11.2:/games/plantsvszombies.tar.gz
          dest: /home/test/.wine/drive_c/games/
          owner: test
          group: test
          remote_src: yes

      - name: Download shortcut for plantsvszombies
        get_url:
          url: http://10.200.11.2:/games/plantsvszombies.desktop
          dest: /home/test/.local/share/applications/
          owner: test
          group: test
          mode: '0555'
### forbid test user to delete shortcuts
#      - name: Recursively change ownership of games shortcuts directory
#        file:
#          path: /home/test/Desktop/Games/
#          state: directory
#          recurse: yes
#          owner: root
#          group: root
