all:
  hosts:
    zslgw.local:
      inet_iface: "enp0s3"
      inet_ip: "10.0.2.15"
      internal_iface: "enp0s8"
      internal_ip: "10.100.0.1"
      internal_net: "10.100.0.0"
      internal_mask: "255.255.255.0"
  children:
    routers:
      hosts:
        zslgw.local:
    dhcp_servers:
      hosts:
        zslgw.local:
          dhcp_iface: "{{ internal_iface }}"
          dhcp_net: "{{ internal_net }}"
          dhcp_mask: "{{ internal_mask }}"
          dhcp_range: "10.100.0.10 10.100.0.200"
          dhcp_gw: "{{ internal_ip }}"
          dhcp_dns: "1.1.1.1, 1.0.0.1"
          dhcp_pxeserver: "{{ internal_ip }}"
          dhcp_pxefile: "bionic/pxelinux.0"
    pxe_servers:
      hosts:
        zslgw.local:
          pxe_addr: "{{ internal_ip }}"
          preseed_addr: "{{ internal_ip }}"
          preseed_desktop: "http://{{ preseed_addr }}/preseed-desktop.txt"
          preseed_server: "http://{{ preseed_addr }}/preseed-server.txt"
    preseed_servers:
      hosts:
        zslgw.local:
    local_servers:
      hosts:
        test-server.zsl.bg:
    clients:
      hosts:
        test-client.zsl.bg:
